# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a base Python image that meets the version requirement
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install the build system
RUN pip install hatchling

# Copy pyproject.toml and the source code
COPY pyproject.toml /app/
COPY src /app/src

# Install the package
RUN pip install .

# Set environment variables for Snowflake
ENV ACCOUNT=your_account
ENV WAREHOUSE=your_warehouse
ENV USER=your_user
ENV PASSWORD=your_password
ENV ROLE=your_role
ENV DATABASE=your_database
ENV SCHEMA=your_schema

# Expose port if required by the application, assuming 8000 for example
EXPOSE 8000

# Command to run the server
ENTRYPOINT ["mcp_snowflake_server"]
